<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WinUia.TestApp\WinUia.TestApp.csproj" ReferenceOutputAssembly="false" />
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>AppPath.TestApp</_Parameter1>
      <_Parameter2>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\WinUia.TestApp\bin\$(Configuration)\$(TargetFramework)\WinUia.TestApp.exe'))</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
